# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  main: main.go
  binary: ontology
  ldflags:
    - -s -w --X github.com/ontio/ontology/common/config.Version={{.Version}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64  
-
  main: sigsvr.go
  binary: sigsvr
  ldflags:
    - -s -w --X github.com/ontio/ontology/common/config.Version={{.Version}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64 
archive:
  replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip        
  files:
    - pkg/config.ini
    - pkg/config.json
    - pkg/ontology.service
    - pkg/setup.sh  
checksum:
  name_template: 'checksums.txt'
git:
  short_hash: true  
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
